version: "3.7"

services:
  juegazo:
    build:
      context: .
      dockerfile: Dockerfile
    image: juegazo
    container_name: juegazo-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
